name: Run standalone executable

on: [push]

jobs:
  standalone-executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.0.0"
      - name: Install dependencies
        run: npm install
      - name: Build the executable
        run: ./scripts/sea.sh
      - name: Test the executable
        run: |
          ./modular-cli foo
          ./modular-cli bar
          ./modular-cli heavy
